# Generated by Django 4.2 on 2025-12-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefono_tutor',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del padre/madre o apoderado', max_length=15, verbose_name='Teléfono del tutor'),
        ),
    ]
