# Generated by Django 4.2 on 2026-01-13 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_telefono_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
    ]
