# Generated by Django 4.2 on 2025-12-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultorio', models.CharField(default='Consultorio Dental', help_text='Nombre del consultorio', max_length=200)),
                ('nombre_doctor', models.CharField(blank=True, help_text='Nombre del doctor/a principal', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo del consultorio (recomendado: 200x200px, PNG con fondo transparente)', null=True, upload_to='configuracion/logos/')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254)),
                ('direccion', models.TextField(blank=True, help_text='Dirección del consultorio')),
                ('sitio_web', models.URLField(blank=True, help_text='Sitio web (opcional)')),
                ('facebook', models.URLField(blank=True, help_text='URL de Facebook')),
                ('instagram', models.URLField(blank=True, help_text='URL de Instagram')),
            ],
            options={
                'verbose_name': 'Configuración del Consultorio',
                'verbose_name_plural': 'Configuración del Consultorio',
            },
        ),
    ]
