# Generated by Django 4.2 on 2025-12-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionconsultorio',
            name='modulo_programa_salud_activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, se ocultará la pestaña y funcionalidades de Programa Salud.', verbose_name='Activar Módulo Programa Salud-Confort'),
        ),
        migrations.AddField(
            model_name='configuracionconsultorio',
            name='modulo_protocolos_activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, se ocultará la pestaña y funcionalidades de Protocolo Niños.', verbose_name='Activar Módulo Protocolo Niños'),
        ),
    ]
