# Generated by Django 4.2 on 2025-12-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracionconsultorio_modulo_programa_salud_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionconsultorio',
            name='imagen_login',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la pantalla de inicio de sesión (recomendado: 1920x1080px)', null=True, upload_to='configuracion/login/'),
        ),
    ]
