# Generated by Django 4.2 on 2025-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_configuracionconsultorio_imagen_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionconsultorio',
            name='tema_sidebar',
            field=models.CharField(choices=[('light', 'Clásico (Blanco)'), ('blue', 'Midnight Blue (Azul Corporativo)'), ('obsidian', 'Obsidian Slate (Gris Moderno)'), ('carbon', 'Carbon Total (Negro Alto Contraste)'), ('rose', 'Rose Premium (Estilo Doctora)')], default='rose', help_text='Selecciona el esquema de colores para el menú lateral.', max_length=20, verbose_name='Tema de la Barra Lateral'),
        ),
    ]
