# Generated by Django 4.2 on 2025-12-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracionconsultorio_tema_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionconsultorio',
            name='tema_sidebar',
            field=models.CharField(choices=[('rose', 'Rose Premium (Estilo Doctora)'), ('light', 'Clásico (Blanco)'), ('blue', 'Midnight Blue (Azul Corporativo)'), ('obsidian', 'Obsidian Slate (Gris Moderno)'), ('carbon', 'Carbon Total (Negro Alto Contraste)'), ('emerald', 'Emerald Executive (Verde Elegante)'), ('royal', 'Royal Violet (Púrpura Intenso)'), ('ocean', 'Ocean Teal (Turquesa Profundo)')], default='rose', help_text='Selecciona el esquema de colores para el menú lateral.', max_length=20, verbose_name='Tema de la Barra Lateral'),
        ),
    ]
