# Generated by Django 5.2.8 on 2025-12-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=50, unique=True, verbose_name='Tipo de Integración')),
                ('activo', models.BooleanField(default=False, help_text='Activar/desactivar esta integración', verbose_name='Activo')),
                ('webhook_url', models.URLField(blank=True, help_text='URL del webhook de Pabbly Connect', verbose_name='URL del Webhook')),
                ('configuracion_json', models.JSONField(blank=True, default=dict, help_text='Configuración extra en formato JSON', verbose_name='Configuración Adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Integración',
                'verbose_name_plural': 'Configuraciones de Integraciones',
            },
        ),
        migrations.CreateModel(
            name='SincronizacionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita_id', models.IntegerField(help_text='ID de la cita en el sistema', verbose_name='ID de la Cita')),
                ('paciente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('google_event_id', models.CharField(blank=True, max_length=255, verbose_name='ID del Evento en Google')),
                ('fecha_sincronizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Sincronización')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('datos_enviados', models.JSONField(default=dict, verbose_name='Datos Enviados')),
            ],
            options={
                'verbose_name': 'Sincronización de Calendario',
                'verbose_name_plural': 'Sincronizaciones de Calendario',
                'ordering': ['-fecha_sincronizacion'],
            },
        ),
    ]
