# Generated by Django 5.2.8 on 2025-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_imagennota_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagennota',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagennota',
            name='imagen_local',
            field=models.ImageField(blank=True, null=True, upload_to='notas/imagenes/', verbose_name='Imagen local (opcional)'),
        ),
        migrations.AddField(
            model_name='imagennota',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Opcional: sube la imagen a Google Drive y pega el enlace aquí', null=True, verbose_name='URL de imagen (Google Drive o servicio externo)'),
        ),
        migrations.AddField(
            model_name='imagennota',
            name='tipo',
            field=models.CharField(choices=[('local', 'Local'), ('externa', 'Externa (Drive)')], default='local', max_length=10, verbose_name='Tipo de imagen'),
        ),
    ]
