# Generated by Django 4.2 on 2025-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('contenido', models.TextField(help_text='Usa {paciente} para el nombre, {fecha} para fechas, etc.', verbose_name='Contenido del Mensaje')),
                ('categoria', models.CharField(choices=[('CUMPLE', 'Cumpleaños'), ('CITA', 'Recordatorio Cita'), ('PAGO', 'Cobranza/Pago'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Categoría')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensajes',
            },
        ),
    ]
