# Generated by Django 4.2 on 2026-01-02 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso_grafico_ingresos', models.BooleanField(default=False, help_text='Permite visualizar el gráfico de barras de ingresos en el Dashboard.', verbose_name='Ver Gráfico de Ingresos')),
                ('permiso_cobranza_pendiente', models.BooleanField(default=False, help_text='Permite ver el widget de pacientes con deudas en el Dashboard.', verbose_name='Ver Cobranza Pendiente')),
                ('permiso_reportes', models.BooleanField(default=False, help_text='Permite acceder al módulo completo de reportes desde el menú.', verbose_name='Acceso a Reportes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
