# Generated by Django 4.2 on 2025-12-12 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_telefono_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora', models.TimeField(verbose_name='Hora de la Cita')),
                ('duracion_minutos', models.IntegerField(default=30, help_text='Duración estimada de la cita en minutos', verbose_name='Duración (minutos)')),
                ('motivo', models.CharField(blank=True, help_text='Ej: Limpieza dental, Control, Extracción, etc.', max_length=200, verbose_name='Motivo de la Cita')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre la cita', verbose_name='Notas Adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20, verbose_name='Estado de la Cita')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío del Recordatorio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora'], name='citas_cita_fecha_46fbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='citas_cita_pacient_dceff6_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
    ]
