# Generated by Django 4.2 on 2025-12-10 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_telefono_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lado_predominante', models.CharField(blank=True, choices=[('D', 'Derecho'), ('I', 'Izquierdo')], max_length=1, null=True, verbose_name='Lado predominante al masticar')),
                ('ventana_nasal', models.CharField(blank=True, choices=[('D', 'Derecho'), ('I', 'Izquierdo')], max_length=1, null=True, verbose_name='Ventana nasal más cerrada')),
                ('sss_respiracion_oral', models.BooleanField(default=False, verbose_name='Respiración oral / Boca seca')),
                ('sss_calidad_sueno', models.BooleanField(default=False, verbose_name='Calidad del sueño / Ronquido / Apnea')),
                ('sss_gingivitis', models.BooleanField(default=False, verbose_name='Gingivitis / Enf. periodontal / Policaries')),
                ('sss_faringitis', models.BooleanField(default=False, verbose_name='Faringitis crónica')),
                ('sss_atm', models.BooleanField(default=False, verbose_name='Desorden ATM / CAT / Bruxismo')),
                ('sss_reflujos', models.BooleanField(default=False, verbose_name='Reflujos / Hernia / Trastornos digestivos')),
                ('sss_cefaleas', models.BooleanField(default=False, verbose_name='Cefaleas, migrañas, vértigos')),
                ('sss_dolor_cervical', models.BooleanField(default=False, verbose_name='Dolor cervical... dolores')),
                ('sss_patologia_homolateral', models.BooleanField(default=False, verbose_name='Patología diversa homolateral')),
                ('sss_masticacion_unilateral', models.BooleanField(default=False, verbose_name='Masticación unilateral (leyes)')),
                ('sss_astenia', models.BooleanField(default=False, verbose_name='Astenia, agotamiento')),
                ('sss_ansiedad', models.BooleanField(default=False, verbose_name='Ansiedad, depresión')),
                ('sss_alergias', models.BooleanField(default=False, verbose_name='Alergias, rinitis, asma')),
                ('sss_hipertension', models.BooleanField(default=False, verbose_name='Hipertensión, riesgo cardiovascular')),
                ('otras_patologias', models.TextField(blank=True, verbose_name='Otras patologías')),
                ('medicacion', models.TextField(blank=True, verbose_name='Medicación')),
                ('intervenciones_previas', models.TextField(blank=True, verbose_name='Intervenciones previas')),
                ('ejercicio_fisico_desc', models.TextField(blank=True, verbose_name='Ejercicio físico (Descripción)')),
                ('habito_fumador', models.BooleanField(default=False, verbose_name='Fumador')),
                ('habito_bebedor', models.BooleanField(default=False, verbose_name='Bebedor')),
                ('enjuagues_manana', models.BooleanField(default=False, verbose_name='Enjuagues Aceite: Mañana')),
                ('enjuagues_tarde', models.BooleanField(default=False, verbose_name='Enjuagues Aceite: Tarde')),
                ('acuaconfort_asignado', models.BooleanField(default=False, verbose_name='AcuaConfort Asignado')),
                ('placa_talla', models.CharField(blank=True, max_length=50, verbose_name='Talla Placa/Deglu')),
                ('placa_3_ratos', models.BooleanField(default=False, verbose_name='Placa: 3 ratos día')),
                ('placa_noche', models.BooleanField(default=False, verbose_name='Placa: Todas las noches')),
                ('nariz_talla', models.CharField(blank=True, max_length=50, verbose_name='Talla NarizConfort')),
                ('nariz_uso', models.CharField(blank=True, choices=[('D', 'Derecho'), ('I', 'Izquierdo'), ('B', 'Bilateral')], max_length=1, null=True, verbose_name='Uso NarizConfort')),
                ('hueso_aceituna', models.BooleanField(default=False, verbose_name='Hueso de aceituna')),
                ('vaselina_labios', models.BooleanField(default=False, verbose_name='Vaselina o cacao')),
                ('alimentacion_lado', models.CharField(blank=True, choices=[('D', 'Derecho'), ('I', 'Izquierdo')], max_length=1, null=True, verbose_name='Masticar por lado')),
                ('ali_fruta_bocados', models.BooleanField(default=False, verbose_name='Fruta entera a bocados')),
                ('ali_evita_carbonatadas', models.BooleanField(default=False, verbose_name='Evita carbonatadas')),
                ('ali_reduce_lacteos', models.BooleanField(default=False, verbose_name='Reduce lácteos/azúcar/harinas')),
                ('regla_321_comer', models.BooleanField(default=False, verbose_name='No comer 3h antes dormir')),
                ('regla_321_beber', models.BooleanField(default=False, verbose_name='No beber 2h antes')),
                ('regla_321_pantallas', models.BooleanField(default=False, verbose_name='No pantallas 1h antes')),
                ('ej_caminata_1h', models.BooleanField(default=False, verbose_name='Caminata 1 hora')),
                ('ej_con_huesito', models.BooleanField(default=False, verbose_name='Con huesito en boca')),
                ('ej_labios_pegados', models.BooleanField(default=False, verbose_name='Labios pegados al caminar')),
                ('ej_pesas', models.BooleanField(default=False, verbose_name='Levantar pesas (masa muscular)')),
                ('reducir_tabaco_alcohol', models.BooleanField(default=False, verbose_name='Reducir tabaco y alcohol')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_salud', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Programa Salud',
                'verbose_name_plural': 'Programas Salud',
                'ordering': ['-fecha'],
            },
        ),
    ]
