# Generated by Django 4.2 on 2025-12-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_telefono_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INICIAL', 'Inicial'), ('EVOLUCION', 'Evolución')], default='INICIAL', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_id', models.IntegerField(help_text='Número de diente según sistema ISO (11-85)')),
                ('cara', models.CharField(choices=[('V', 'Vestibular'), ('L', 'Lingual/Palatino'), ('M', 'Mesial'), ('D', 'Distal'), ('O', 'Oclusal/Incisal'), ('C', 'Completo (Diente entero)'), ('R', 'Raíz')], max_length=1)),
                ('estado', models.CharField(choices=[('SANO', 'Sano'), ('CARIES', 'Caries'), ('OBTURADO', 'Obturado/Resina'), ('AUSENTE', 'Ausente'), ('CORONA', 'Corona'), ('TRATAMIENTO_CONDUCTO', 'Tratamiento de Conducto'), ('EXTRACCION_INDICADA', 'Indicado para Extracción'), ('SELLANTE', 'Sellante'), ('PROTESIS', 'Prótesis')], max_length=50)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='odontograma.odontograma')),
            ],
        ),
    ]
