# Generated by Django 4.2 on 2025-12-10 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odontograma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallazgo',
            name='notas',
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='comentario',
            field=models.TextField(blank=True, help_text='Notas específicas sobre este hallazgo', null=True),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='fecha_hallazgo',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='estado',
            field=models.CharField(choices=[('SANO', 'Sano'), ('CARIES', 'Caries'), ('OBTURADO', 'Obturado/Resina'), ('AUSENTE', 'Ausente'), ('CORONA', 'Corona'), ('TRATAMIENTO_CONDUCTO', 'Tratamiento de Conducto'), ('EXTRACCION_INDICADA', 'Indicado para Extracción'), ('SELLANTE', 'Sellante'), ('PROTESIS', 'Prótesis'), ('ORTODONCIA', 'Ortodoncia (Brackets)')], max_length=50),
        ),
        migrations.CreateModel(
            name='LogOdontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='odontograma.odontograma')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
