# Generated by Django 4.2 on 2025-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0002_remove_hallazgo_notas_hallazgo_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgo',
            name='estado',
            field=models.CharField(choices=[('SANO', 'Sano / Borrar'), ('CARIES', 'Caries'), ('OBTURADO', 'Obturado / Resina'), ('CORONA', 'Corona'), ('AUSENTE', 'Ausente'), ('ENDODONCIA', 'Endodoncia'), ('SELLANTE', 'Sellante'), ('BRACKET', 'Bracket'), ('RETENEDOR', 'Retenedor'), ('APARATO_REMOVIBLE', 'Aparato Removible'), ('EXTRACCION_PROGRAMADA', 'Extracción Programada'), ('FRACTURA', 'Fractura'), ('IMPLANTE', 'Implante'), ('PUENTE', 'Puente'), ('PROTESIS_PARCIAL', 'Prótesis Parcial'), ('PROTESIS_TOTAL', 'Prótesis Total'), ('EN_ERUPCION', 'En Erupción'), ('DIENTE_RETENIDO', 'Diente Retenido')], max_length=50),
        ),
    ]
