# Generated by Django 4.2 on 2026-01-13 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odontograma', '0003_alter_hallazgo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logodontograma',
            name='accion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logodontograma',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FotoDiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente_id', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='odontograma_fotos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_diente', to='odontograma.odontograma')),
            ],
        ),
    ]
