# Generated by Django 4.2 on 2026-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontograma', '0004_alter_logodontograma_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontograma',
            name='tipo_denticion',
            field=models.CharField(choices=[('adult', 'Adulto'), ('child', 'Niño'), ('mixed', 'Mixta')], default='adult', max_length=10),
        ),
    ]
